let Lista = [
	{"Titulo":"Ven, es hora de adorarle","Tiempo":"116","Size":"4"},
	{"Titulo":"Infinito Dios","Tiempo":"102","Secuencia":"infinitoDios-Sec.mp3","Size":"4"},
	{"Titulo":"Alabemos, extaltemos","Tiempo":"150","Size":"4"},
	{"Titulo":"Mi alma anhela","Tiempo":"100","Secuencia":"miAlmaAnhela-Sec.mp3","Size":"4"},
	{"Titulo":"Vamos a cantar","Tiempo":"146","Secuencia":"vamosaCantar-Sec.mp3","Size":"4"},
	{"Titulo":"A quien ire?","Tiempo":"84","Secuencia":"aQuienIre.mp3","Size":"4"},
	{"Titulo":"Abre los cielos","Tiempo":"80","Size":"4"},
	{"Titulo":"Abre mis ojos","Tiempo":"127","Size":"4"},
	{"Titulo":"Agnus Dei","Tiempo":"127","Size":"4"},
	{"Titulo":"Sera llena la tierra","Tiempo":"147","Size":"4"},
	{"Titulo":"Bueno es alabar","Tiempo":"119","Size":"4"},
	{"Titulo":"Al que me ciñe","Tiempo":"104","Size":"4"},
	{"Titulo":"A sus pies","Tiempo":"98","Secuencia":[{"Descripcion":"Secuencia Corto","Archivo":"aSusPies-Sec.mp3"},{"Descripcion":"Secuencia Solo","Archivo":"aSusPies-SecSolo.mp3"},{"Descripcion":"Secuencia Completa","Archivo":"aSusPies-SecCompleta.mp3"}],"Size":"4"},
	{"Titulo":"Ven, Espíritu","Tiempo":"150","Secuencia":[{"Descripcion":"Secuencia Dm","Archivo":"VenEspiritu-SecDm.mp3"},{"Descripcion":"Secuencia Em","Archivo":"VenEspiritu-SecEm.mp3"}],"Size":"4"},
	{"Titulo":"Cada mañana","Tiempo":"76","Size":"4"},
	{"Titulo":"Con mi Dios","Tiempo":"154","Size":"4"},
	{"Titulo":"Cristo es mi Señor","Tiempo":"100","Size":"4"},
	{"Titulo":"Dios no nos trajo hasta aquí","Tiempo":"130","Size":"4"},
	{"Titulo":"Eres Todopoderoso","Tiempo":"125","Secuencia":"EresTodopoderoso-Sec1.mp3","Size":"4"},
	{"Titulo":"El jardín","Tiempo":"86","Size":"4"},
	{"Titulo":"El Señor es mi Pastor","Tiempo":"128","Size":"4"},
	{"Titulo":"El que está en Cristo","Tiempo":"107","Size":"4"},
	{"Titulo":"Hossana","Tiempo":"146","Secuencia":"hossana-Sec1.mp3","Size":"4"},
	{"Titulo":"Santo (Coalo Zamorano)","Tiempo":"140","Size":"4"},
	{"Titulo":"Santo (Redimidos)","Tiempo":"125","Size":"4"},
	{"Titulo":"Vine adorar a Dios","Tiempo":"112","Size":"4"},
	{"Titulo":"El ejercito de Dios","Tiempo":"142","Size":"4"},
	{"Titulo":"Hoy te vengo a bendecir","Tiempo":"123","Size":"4"},
	{"Titulo":"Te alabare mi buen Jesús","Tiempo":"119","Secuencia":"teAlabaremiBuenJesus-Sec1.mp3","Size":"4"},
	{"Titulo":"Santo por siempre","Tiempo":"144","Secuencia":"SantoPorSiempre-Sec1.mp3","Size":"4"},
	{"Titulo":"Has aumentado","Tiempo":"112","Secuencia":"hasAumentado-Sec1.mp3","Size":"4"},
	{"Titulo":"Al que es digno","Tiempo":"111","Secuencia":"alqueesDigno-Sec1.mp3","Size":"4"},
	{"Titulo":"Increible","Tiempo":"132","Secuencia":"Increible-Sec1.mp3","Size":"4"},
	{"Titulo":"Rey de gloria","Tiempo":"98","Size":"4"},
	{"Titulo":"Me gozaré","Tiempo":"140","Size":"4"},
	{"Titulo":"Esta cayendo","Tiempo":"130","Size":"4"},
	{"Titulo":"Tu","Tiempo":"122","Size":"4"},
	{"Titulo":"Cuan grande es Dios","Tiempo":"78","Size":"4"},
	{"Titulo":"Al estar aquí","Tiempo":"114","Size":"4"},
	{"Titulo":"A ti","Tiempo":"113","Size":"4"},
	{"Titulo":"Como el siervo","Tiempo":"116","Size":"4"},
	{"Titulo":"Conozco que todo lo puedes","Tiempo":"120","Size":"4"},
	{"Titulo":"Damos honor a ti","Tiempo":"87","Size":"4"},
	{"Titulo":"Exáltate","Tiempo":"110","Size":"4"},
	{"Titulo":"De gloria en gloria (Marcos Witt)","Tiempo":"114","Size":"4"},
	{"Titulo":"Gracias","Tiempo":"98","Size":"4"},
	{"Titulo":"Hacemos hoy","Tiempo":"98","Size":"4"},
	{"Titulo":"Heme aquí (JAR)","Tiempo":"95","Size":"4"},
	{"Titulo":"Cuan glorioso es el cambio","Tiempo":"120","Size":"4"},
	{"Titulo":"Has cambiado","Tiempo":"139","Size":"4"},
	{"Titulo":"Oh Adonai","Tiempo":"139","Size":"4"},
	{"Titulo":"Hoy y siempre, te alabaré","Tiempo":"140","Size":"4"},
	{"Titulo":"Jesús es Señor","Tiempo":"110","Size":"4"},
	{"Titulo":"Jesús mi fiel amigo","Tiempo":"110","Size":"4"},
	{"Titulo":"La casa de Dios","Tiempo":"143","Secuencia":[{"Descripcion":"Secuencia","Archivo":"LaCasaDeDios.mp3"},{"Descripcion":"Secuencia Solo","Archivo":"LaCasaDeDios-SecSolo.mp3"}],"Size":"4"},
	{"Titulo":"Levántate Señor","Tiempo":"131","Size":"4"},
	{"Titulo":"Libre","Tiempo":"150","Size":"4"},
	{"Titulo":"Llévame","Tiempo":"120","Size":"4"},
	{"Titulo":"Manda Señor","Tiempo":"115","Size":"4"},
	{"Titulo":"Abre los cielos hoy","Tiempo":"146","Secuencia":[{"Descripcion":"Secuencia","Archivo":"AbreLosCielosHoy-Sec1.mp3"},{"Descripcion":"Secuencia Solo","Archivo":"AbreLosCielosHoy-SecSolo.mp3"}],"Size":"4"},
	{"Titulo":"No me soltarás","Tiempo":"83","Size":"4"},
	{"Titulo":"Cerca de ti","Tiempo":"105","Size":"4"},
	{"Titulo":"Celebra victorioso","Tiempo":"182","Size":"4"},
	{"Titulo":"Celebraré tu amor","Tiempo":"102","Size":"4"},
	{"Titulo":"Con tu sangre","Tiempo":"112","Size":"4"},
	{"Titulo":"De tal manera","Tiempo":"64","Size":"4"},
	{"Titulo":"Siempre contigo","Tiempo":"126","Secuencia":"siempreContigo-Sec1.mp3","Size":"4"},
	{"Titulo":"Tu mereces gloria","Tiempo":"120","Secuencia":"tuMerecesGloria-Sec1.mp3","Size":"4"},
	{"Titulo":"Dios ha sido bueno","Tiempo":"121","Size":"4"},
	{"Titulo":"Porque bueno es Dios","Tiempo":"104","Size":"4"},
	{"Titulo":"Con manos vacías","Tiempo":"102","Size":"4"},
	{"Titulo":"Con mis manos levantadas","Tiempo":"64","Size":"4"},
	{"Titulo":"Dios el mas grande","Tiempo":"123","Size":"4"},
	{"Titulo":"Doxologia","Tiempo":"90","Size":"4"},
	{"Titulo":"Alabadle","Tiempo":"90","Size":"4"},
	{"Titulo":"Creo en ti","Tiempo":"70","Size":"4"},
	{"Titulo":"Al que esta sentado en el trono","Tiempo":"71","Size":"4"},
	{"Titulo":"Esperamos en ti","Tiempo":"117","Size":"4"},
	{"Titulo":"Tu nos creaste","Tiempo":"79","Size":"4"},
	{"Titulo":"Tu dulce amor","Tiempo":"100","Secuencia":"tuDulceAmor-Sec1.mp3","Size":"4"},
	{"Titulo":"Dios imparable","Tiempo":"164","Secuencia":"DiosImparable-Sec1.mp3","Size":"6"},
	{"Titulo":"Inagotable","Tiempo":"168","Secuencia":"inagotable-Sec1.mp3","Size":"6"},
	{"Titulo":"Lo harás otra vez","Tiempo":"86","Secuencia":"LoHarasOtraVez-Sec1.mp3","Size":"4"},
	{"Titulo":"Gracia Sublime es","Tiempo":"100","Secuencia":"GraciaSublimeEs-Sec1.mp3","Size":"4"},
	{"Titulo":"Abres caminos","Tiempo":"136","Secuencia":"AbresCaminos-Sec1.mp3","Size":"4"},
	{"Titulo":"Bienvenido Espíritu","Tiempo":"98","Secuencia":"BienvenidoEspiritu-Sec1.mp3","Size":"4"},
	{"Titulo":"Me has dado Libertad","Tiempo":"100","Size":"4"},
	{"Titulo":"El Señor esta en este lugar","Tiempo":"140","Size":"4"},
	{"Titulo":"Un adorador","Tiempo":"144","Size":"4"},
	{"Titulo":"Somos Libres","Tiempo":"145","Size":"4"},
	{"Titulo":"El camino del Señor","Tiempo":"150","Size":"4"},
	{"Titulo":"Digno","Tiempo":"130","Size":"4"},
	{"Titulo":"La bondad de Dios","Tiempo":"126","Size":"4"},
	{"Titulo":"En tu Luz","Tiempo":"138","Secuencia":[{"Descripcion":"Secuencia E","Archivo":"EnTuLuz-E.mp3"},{"Descripcion":"Secuencia D","Archivo":"EnTuLuz-D.mp3"}],"Size":"4"},
	{"Titulo":"Mas el Dios","Tiempo":"124","Size":"4"},
	{"Titulo":"Grande y fuerte","Tiempo":"150","Size":"4"},
	{"Titulo":"Acuérdate","Tiempo":"104","Size":"4"},
	{"Titulo":"Conozco que eres Santo","Tiempo":"120","Size":"4"},
	{"Titulo":"Cantaré de tu Amor","Tiempo":"166","Size":"4"},
	{"Titulo":"Somos el pueblo","Tiempo":"95","Size":"4"},
	{"Titulo":"Te alabamos","Tiempo":"96","Size":"4"},
	{"Titulo":"Esperar en ti","Tiempo":"105","Size":"4"},
	{"Titulo":"Que sería de mi","Tiempo":"109","Size":"4"},
	{"Titulo":"Tu Pueblo dice Gracias","Tiempo":"125","Size":"4"},
	{"Titulo":"Quien como el Señor?","Tiempo":"98","Size":"4"},
	{"Titulo":"No hay lugar mas alto","Tiempo":"136","Size":"4"},
	{"Titulo":"Al alto y sublime","Tiempo":"108","Size":"4"},
	{"Titulo":"Señor eres Fiel","Tiempo":"129","Size":"4"},
	{"Titulo":"Mi Dios es real","Tiempo":"144","Size":"4"},
	{"Titulo":"Yo quiero mas de ti","Tiempo":"118","Size":"4"},
	{"Titulo":"Dios de Amor","Tiempo":"160","Size":"3"},
	{"Titulo":"Es por ti","Tiempo":"80","Size":"4"},
	{"Titulo":"Por siempre","Tiempo":"128","Size":"4"},
	{"Titulo":"Yo te busco","Tiempo":"85","Size":"4"},
	{"Titulo":"Hoy es tiempo","Tiempo":"142","Size":"4"},
	{"Titulo":"Quiero buscarte mas","Tiempo":"123","Size":"4"},
	{"Titulo":"Dulce Refugio","Tiempo":"124","Size":"4"},
	{"Titulo":"Bueno es Dios","Tiempo":"120","Size":"4"},
	{"Titulo":"Levanto mis manos","Tiempo":"126","Size":"4"},
	{"Titulo":"Gloriosa Cruz","Tiempo":"90","Size":"4"},
	{"Titulo":"Manda lluvia","Tiempo":"110","Size":"4"},
	{"Titulo":"Al estar ante ti","Tiempo":"144","Size":"4"},
	{"Titulo":"En totalidad a ti","Tiempo":"115","Size":"4"},
	{"Titulo":"Entra en la presencia","Tiempo":"132","Size":"4"},
	{"Titulo":"Oh Ven!","Tiempo":"126","Size":"4"},
	{"Titulo":"Oh Jesús","Tiempo":"128","Size":"4"},
	{"Titulo":"Bendito Jesús","Tiempo":"123","Size":"4"},
	{"Titulo":"Sentado en su trono","Tiempo":"122","Size":"4"},
	{"Titulo":"Hermoso eres","Tiempo":"110","Size":"4"},
	{"Titulo":"Tu nombre levantaré","Tiempo":"116","Size":"4"},
	{"Titulo":"Rindo mi corazón","Tiempo":"103","Size":"4"},
	{"Titulo":"Espíritu de Dios","Tiempo":"116","Size":"4"},
	{"Titulo":"Amante de Ti","Tiempo":"99","Size":"4"},
	{"Titulo":"Enamorame","Tiempo":"124","Size":"4"},
	{"Titulo":"Es Jesús","Tiempo":"118","Size":"4"},
	{"Titulo":"El Dios que adoramos","Tiempo":"110","Size":"4"},
	{"Titulo":"Tu Nombre","Tiempo":"95","Size":"4"},
	{"Titulo":"Padre del cielo","Tiempo":"136","Size":"4"},
	{"Titulo":"Porque eres digno","Tiempo":"120","Size":"4"},
	{"Titulo":"Gracias Cristo (estribillo)","Tiempo":"72","Size":"4"},
	{"Titulo":"Gracias Cristo (Hillsong)","Tiempo":"158","Size":"4"},
	{"Titulo":"Amarte sólo a ti","Tiempo":"70","Size":"4"},
	{"Titulo":"Oh moradora (alas de águila)","Tiempo":"130","Size":"4"},
	{"Titulo":"Alaba","Tiempo":"140","Size":"4"},
	{"Titulo":"Eres Rey de los cielos","Tiempo":"168","Size":"4"},
	{"Titulo":"Solo de Jesús la sangre","Tiempo":"83","Size":"4"},
	{"Titulo":"Recibe al Rey","Tiempo":"168","Size":"4"},
	{"Titulo":"Pan de vida","Tiempo":"150","Size":"4"},
	{"Titulo":"Celebrad a Cristo","Tiempo":"150","Size":"4"},
	{"Titulo":"Mi Cristo Vive","Tiempo":"136","Size":"4"},
	{"Titulo":"Cristo Vive Hoy","Tiempo":"143","Size":"4"},
	{"Titulo":"El Sacrificio","Tiempo":"147","Size":"4"},
	{"Titulo":"Solo me imagino","Tiempo":"146","Size":"4"},
	{"Titulo":"Dios de Pactos","Tiempo":"136","Size":"4"},
	{"Titulo":"Cuan grande es El (Himno)","Tiempo":"136","Size":"4"},
	{"Titulo":"Te doy gloria","Tiempo":"136","Size":"4"},
	{"Titulo":"Los enemigos de Jehová","Tiempo":"152","Size":"4"},
	{"Titulo":"Al borde (Exáltate)","Tiempo":"112","Size":"4"},
	{"Titulo":"Somos Pueblo","Tiempo":"142","Size":"4"},
	{"Titulo":"Roca eterna","Tiempo":"126","Size":"4"},
	{"Titulo":"Haz ganado","Tiempo":"140","Size":"4"},
	{"Titulo":"Llevame al lugar Santísimo","Tiempo":"118","Size":"4"},
	{"Titulo":"Torre Fuerte","Tiempo":"124","Size":"4"},
	{"Titulo":"Tu amor por mi","Tiempo":"106","Size":"4"},
	{"Titulo":"Hermoso Nombre","Tiempo":"136","Secuencia":"HermosoNombre-Sec.mp3","Size":"4"},
	{"Titulo":"Agradecido","Tiempo":"144","Secuencia":"Agradecido-Sec1.mp3","Size":"4"},
	{"Titulo":"Hossana (Hillsong)","Tiempo":"153","Secuencia":"HossanaHilsong-Sec.mp3","Size":"4"},
	{"Titulo":"El es el Rey","Tiempo":"133","Secuencia":"ElesElRey-Sec.mp3","Size":"4"},
	{"Titulo":"Te daré lo mejor","Tiempo":"106","Secuencia":[{"Descripcion":"Secuencia Completa","Archivo":"TeDareLoMejor-Sec1.mp3"},{"Descripcion":"Secuencia Corta","Archivo":"TeDareLoMejor-SecCorta.mp3"},{"Descripcion":"Secuencia Solo","Archivo":"TeDareLoMejor-SecSolo.mp3"}],"Size":"4"},
	{"Titulo":"El Señor es mi Rey","Tiempo":"153","Secuencia":"ElSenorEsMiReyMSM.mp3","Size":"4"},
	{"Titulo":"Los muros caerán","Tiempo":"152","Secuencia":"LosMurosCaeran-Sec1.mp3","Size":"4"},
	{"Titulo":"Santo y Poderoso","Tiempo":"115","Secuencia":"SantoyPoderoso-Sec1.mp3","Size":"4"},
	{"Titulo":"El Gran Yo Soy","Tiempo":"115","Secuencia":"ElGranYoSoy-Sec1.mp3","Size":"4"},
	{"Titulo":"Desde mi interior","Tiempo":"138","Secuencia":"DesdeMiInterior.mp3","Size":"4"},
	{"Titulo":"Soy sano","Tiempo":"105","Secuencia":"SoySano-Sec1.mp3","Size":"4"},
	{"Titulo":"Dios eres mío","Tiempo":"157","Secuencia":"DiosEresMio.mp3","Size":"4"},
	{"Titulo":"Queremos ver","Tiempo":"155","Secuencia":"QueremosVer.mp3","Size":"4"},
	{"Titulo":"No hay otro nombre","Tiempo":"148","Secuencia":"NoHayOtroNombre.mp3","Size":"4"},
	{"Titulo":"Tal como soy","Tiempo":"92","Size":"4"},
	{"Titulo":"A Cristo, solo a Cristo","Tiempo":"145","Size":"4"},
	{"Titulo":"Temprano yo te buscaré","Tiempo":"123","Size":"4"},
	{"Titulo":"Alabanzas dad a Cristo (lento)","Tiempo":"91","Size":"4"},
	{"Titulo":"Alabanzas dad a Cristo (rapido)","Tiempo":"128","Size":"4"},
	{"Titulo":"Levantate y Salvame","Tiempo":"130","Size":"4"},
	{"Titulo":"En los montes, en los valles","Tiempo":"106","Secuencia":"EnLosMontes-Sec.mp3","Size":"4"},
	{"Titulo":"Siento su gloria","Tiempo":"100","Size":"4"},
	{"Titulo":"De gloria en gloria (Marco B.)","Tiempo":"128","Secuencia":"DeGloriaEnGloria-Sec.mp3","Size":"4"},
	{"Titulo":"Oh majestad!","Tiempo":"113","Size":"4"},
	{"Titulo":"Clamor de guerra","Tiempo":"150","Size":"4"},
	{"Titulo":"Pon aceite en mi vida","Tiempo":"138","Size":"4"},
	{"Titulo":"Revisteme","Tiempo":"108","Size":"4"},
	{"Titulo":"Dios incomparable","Tiempo":"156","Size":"4"},
	{"Titulo":"Cantare","Tiempo":"178","Size":"4"},
	{"Titulo":"Eres suficiente","Tiempo":"108","Size":"4"},
	{"Titulo":"El Espíritu de Dios esta aqui","Tiempo":"102","Size":"4"},
	{"Titulo":"Santo es el que vive","Tiempo":"128","Size":"4"}
];