let ListaH = [
	{"Titulo":"Bienaventurados son","hVictoria":"207","Tono":"Bb"},
	{"Titulo":"Santo Santo Santo","hVictoria":"9","Tono":"E"},
	{"Titulo":"A Jesucristo ven sin tardar","hVictoria":"150","Tono":"Bb"},
	{"Titulo":"Tan dulce el Nombre de Jesús","hVictoria":"10","Tono":"C"},
	{"Titulo":"Al Rey de los reyes","hVictoria":"26","Tono":"Dm"},
	{"Titulo":"Tuyo soy Jesús","hVictoria":"217","Tono":"Ab"},
	{"Titulo":"Gloria a ti Jesús Divino","hVictoria":"15","Tono":"Bb"},
	{"Titulo":"Hay un canto nuevo","hVictoria":"21","Tono":"Ab"},
	{"Titulo":"Voy feliz al dulce hogar","hVictoria":"323","Tono":"Ab"},
	{"Titulo":"Oh, mi corazón rebosa","hVictoria":"421","Tono":"C"},
	{"Titulo":"Gozandome yo voy","hVictoria":"418","Tono":"C"},
	{"Titulo":"Yo me siento hoy gosozo","hVictoria":"419","Tono":"D"},
	{"Titulo":"Oigo Decir","hVictoria":"514","Tono":"Bb"},
	{"Titulo":"Grande gozo hay en mi alma","hVictoria":"293","Tono":"Ab"},
	{"Titulo":"Cómo podré estar triste?","hVictoria":"262","Tono":"Db"},
	{"Titulo":"A donde iré?","hVictoria":"-","Tono":"G"},
	{"Titulo":"La senda ancha dejaré","hVictoria":"-","Tono":"G"},
	{"Titulo":"Todo a Cristo yo me rindo","hVictoria":"211","Tono":"D"},
	{"Titulo":"Me hirió el pecado","hVictoria":"19","Tono":"E"},
	{"Titulo":"Oh Dios visitanos","hVictoria":"139","Tono":"F"},
	{"Titulo":"Llena de amor mi camino","hVictoria":"-","Tono":"Ab"},
	{"Titulo":"Somos soldados de la lid","hVictoria":"329","Tono":"F"},
	{"Titulo":"El sabe como","hVictoria":"-","Tono":"Eb"},
	{"Titulo":"Oh proclamad con alegría","hVictoria":"126","Tono":"F"},
	{"Titulo":"Yo espero el día alegre","hVictoria":"113","Tono":"G"},
	{"Titulo":"Oh, cantadmelas otra vez","hVictoria":"45","Tono":"G"},
	{"Titulo":"Firmes y adelante","hVictoria":"351","Tono":"E"},
	{"Titulo":"Dad al Padre toda gloria","hVictoria":"1","Tono":"Eb"},
	{"Titulo":"El Rey ya viene","hVictoria":"-","Tono":"A"},
	{"Titulo":"Mas allá del sol","hVictoria":"526","Tono":"Eb"},
	{"Titulo":"En las aguas del bautismo","hVictoria":"526","Tono":"Eb"},
	{"Titulo":"Junto a la cruz","hVictoria":"190","Tono":"Ab"},
	{"Titulo":"En las olas inmensas","hVictoria":"253","Tono":"Bb"},
	{"Titulo":"Oh, Santísimo","hVictoria":"512","Tono":"D"},
	{"Titulo":"Venid Fieles todos","hVictoria":"-","Tono":"G"},
	{"Titulo":"Oid un son","hVictoria":"85","Tono":"G"},
	{"Titulo":"Noche de Paz","hVictoria":"79","Tono":"C"},
	{"Titulo":"Suenen dulces himnos","hVictoria":"74","Tono":"Bb"},
	{"Titulo":"Tu dejaste tu trono","hVictoria":"75","Tono":"F"},
	{"Titulo":"Cuan glorioso es el cambio","hVictoria":"295","Tono":"A"},
	{"Titulo":"Te loamos, oh Dios","hVictoria":"5","Tono":"G"},
	{"Titulo":"Santo, Santo, Grande","hVictoria":"19","Tono":"G"},
	{"Titulo":"Por la inefable luz","hVictoria":"483","Tono":"Bb"},
	{"Titulo":"Cuan gloriosa será la mañana","hVictoria":"-","Tono":"C"},
	{"Titulo":"Unid los cantos","hVictoria":"522","Tono":"Bb"},
	{"Titulo":"Las cien ovejas","hVictoria":"-","Tono":"F"},
	{"Titulo":"Cuando la trompeta suene","hVictoria":"389","Tono":"Ab"},
	{"Titulo":"Vida eterna Él prometió","hVictoria":"174","Tono":"G"},
	{"Titulo":"Oh no rechaces!","hVictoria":"152","Tono":"F"},
	{"Titulo":"Oh bondad tan infinita!","hVictoria":"54","Tono":"Ab"},
	{"Titulo":"Pecador ven al dulce Jesús","hVictoria":"159","Tono":"G"},
	{"Titulo":"Si del pecado anhelas el perdón","hVictoria":"176","Tono":"F"},
	{"Titulo":"Quieres ser salvo?","hVictoria":"196","Tono":"Bb"},
	{"Titulo":"Un día Cristo volverá","hVictoria":"117","Tono":"Ab"},
	{"Titulo":"Día de victoria","hVictoria":"115","Tono":"Db"},
	{"Titulo":"Los caminos fatigados","hVictoria":"-","Tono":"Bb"},
	{"Titulo":"Hubo quien por mis culpas","hVictoria":"93","Tono":"F"},
	{"Titulo":"En el monte calvario","hVictoria":"474","Tono":"Bb"},
	{"Titulo":"Nos estamos preparando (Aleluya)","hVictoria":"-","Tono":"Bb"},
	{"Titulo":"Es la oración","hVictoria":"338","Tono":"D"},
	{"Titulo":"Cuando estes cansado","hVictoria":"256","Tono":"Bb"},
	{"Titulo":"Que me puede dar perdón?","hVictoria":"189","Tono":"G"},
	{"Titulo":"Cristo esta buscando","hVictoria":"359","Tono":"Ab"},
	{"Titulo":"Trabajad, trabajad!","hVictoria":"362","Tono":"F"},
	{"Titulo":"Mi Jesús ascendió","hVictoria":"111","Tono":"G"},
	{"Titulo":"Marcha de triunfo","hVictoria":"-","Tono":"F"},
	{"Titulo":"Las mujeres trabajan","hVictoria":"-","Tono":"C"},
	{"Titulo":"Jesús es mi Rey soberano","hVictoria":"447","Tono":"Dd"},
	{"Titulo":"Hallé un buen amigo","hVictoria":"-","Tono":"F"},
	{"Titulo":"Cuan grande es El","hVictoria":"17","Tono":"Bb"},
	{"Titulo":"Busca hermano la promesa","hVictoria":"-","Tono":"D"},
	{"Titulo":"Exelso Don","hVictoria":"-","Tono":"G"},
	{"Titulo":"Que mi vida entera esté","hVictoria":"214","Tono":"D"},
	{"Titulo":"Vino a dar un manantial","hVictoria":"-","Tono":"Ab"},
	{"Titulo":"Soy soldado de Cristo","hVictoria":"369","Tono":"F"},
	{"Titulo":"Oh! jamás nos cansaremos","hVictoria":"3","Tono":"Eb"},
	{"Titulo":"Mientras viva","hVictoria":"524","Tono":"D"},
	{"Titulo":"Maestro se encrespan las aguas","hVictoria":"272","Tono":"C"},
	{"Titulo":"Al mundo paz","hVictoria":"-","Tono":"D"},
	{"Titulo":"Al Señor yo le quiero servir","hVictoria":"-","Tono":"Bb"},
	{"Titulo":"Loor a ti mi Dios","hVictoria":"29","Tono":"Ab"},
	{"Titulo":"Tenme brillando","hVictoria":"525","Tono":"Eb"}
];