let ListaH = [
	{"Titulo":"Bienaventurados son","hVictoria":"207","Tono":"Bb"},
	{"Titulo":"Santo Santo Santo","hVictoria":"9","Tono":"E"},
	{"Titulo":"A Jesucristo ven sin tardar","hVictoria":"-","Tono":"Bb"},
	{"Titulo":"Tan dulce el Nombre de Jesús","hVictoria":"10","Tono":"C"},
	{"Titulo":"Al Rey de los reyes","hVictoria":"-","Tono":"Dm"},
	{"Titulo":"Tuyo soy Jesús","hVictoria":"217","Tono":"Ab"},
	{"Titulo":"Gloria a ti Jesús Divino","hVictoria":"15","Tono":"Bb"},
	{"Titulo":"Hay un canto nuevo","hVictoria":"21","Tono":"Ab"},
	{"Titulo":"Voy feliz al dulce hogar","hVictoria":"323","Tono":"Ab"},
	{"Titulo":"Oh, mi corazón rebosa","hVictoria":"421","Tono":"C"},
	{"Titulo":"Gozandome yo voy","hVictoria":"418","Tono":"C"},
	{"Titulo":"Yo me siento hoy gosozo","hVictoria":"419","Tono":"D"},
	{"Titulo":"Oigo Decir","hVictoria":"-","Tono":"Bb"},
	{"Titulo":"Grande gozo hay en mi alma","hVictoria":"293","Tono":"Ab"},
	{"Titulo":"Cómo podré estar triste?","hVictoria":"-","Tono":"Db"},
	{"Titulo":"A donde iré?","hVictoria":"-","Tono":"G"},
	{"Titulo":"La senda ancha dejaré","hVictoria":"-","Tono":"G"},
	{"Titulo":"Todo a Cristo yo me rindo","hVictoria":"211","Tono":"D"},
	{"Titulo":"Me hirió el pecado","hVictoria":"-","Tono":"E"},
	{"Titulo":"Oh Dios visitanos","hVictoria":"139","Tono":"F"},
	{"Titulo":"Llena de amor mi camino","hVictoria":"-","Tono":"Ab"},
	{"Titulo":"Somos soldados de la lid","hVictoria":"-","Tono":"F"},
	{"Titulo":"El sabe como","hVictoria":"-","Tono":"Eb"},
	{"Titulo":"Oh proclamad con alegría","hVictoria":"126","Tono":"F"},
	{"Titulo":"Yo espero el día alegre","hVictoria":"113","Tono":"G"},
	{"Titulo":"Oh, cantadmelas otra vez","hVictoria":"45","Tono":"G"},
	{"Titulo":"Firmes y adelante","hVictoria":"-","Tono":"E"},
	{"Titulo":"Dad al Padre toda gloria","hVictoria":"1","Tono":"Eb"},
	{"Titulo":"El Rey ya viene","hVictoria":"-","Tono":"A"},
	{"Titulo":"Mas allá del sol","hVictoria":"526","Tono":"Eb"},
	{"Titulo":"En las aguas del bautismo","hVictoria":"526","Tono":"Eb"},
	{"Titulo":"Junto a la cruz","hVictoria":"-","Tono":"Ab"},
	{"Titulo":"En las olas inmensas","hVictoria":"-","Tono":"Bb"},
	{"Titulo":"Oh, Santísimo","hVictoria":"512","Tono":"D"},
	{"Titulo":"Venid Fieles todos","hVictoria":"-","Tono":"G"},
	{"Titulo":"Oid un son","hVictoria":"85","Tono":"G"},
	{"Titulo":"Noche de Paz","hVictoria":"79","Tono":"C"},
	{"Titulo":"Suenen dulces himnos","hVictoria":"74","Tono":"Bb"},
	{"Titulo":"Tu dejaste tu trono","hVictoria":"75","Tono":"F"},
	{"Titulo":"Cuan glorioso es el cambio","hVictoria":"295","Tono":"A"},
	{"Titulo":"Te loamos, oh Dios","hVictoria":"5","Tono":"G"},
	{"Titulo":"Santo, Santo, Grande","hVictoria":"19","Tono":"G"},
	{"Titulo":"Por la inefable luz","hVictoria":"483","Tono":"Bb"},
	{"Titulo":"Cuan gloriosa será la mañana","hVictoria":"-","Tono":"C"},
	{"Titulo":"Unid los cantos","hVictoria":"522","Tono":"Bb"},
	{"Titulo":"Las cien ovejas","hVictoria":"-","Tono":"F"},
	{"Titulo":"Cuando la trompeta suene","hVictoria":"-","Tono":"Ab"},
	{"Titulo":"Vida eterna Él prometió","hVictoria":"174","Tono":"G"}
];